instala bootstrap
Augustoqtn/blog pull request #3
Opened 2021-04-26 20:25 UTC by Augustoqtn

2021-04-26 21:24 UTC, mjacobus commented
O arquivo todo.txt está vazio. Pode ser removido ou vai precisar dele para outra coisa?

2021-04-26 21:24 UTC, mjacobus requested changes
Muito bom, parabéns!

Apenas umas pequenas alteraçõezinhas pra limpar.

2021-04-26 21:24 UTC, mjacobus commented on config/database.yml
> +#hdshudhsuhdushudhuh
Pode reverter esta mudança?

2021-04-27 17:30 UTC, mjacobus commented on config/database.yml
> +#
Tu deixou um espaço aqui. Precisa remover este espaço também.

No teu commit, quando tu remover o espaço, não coloca "configura bootstrap", pois isto não é o que tu está fazendo, mas sim, está removendo um espaço.

2021-04-27 17:34 UTC, merged

2021-04-27 17:35 UTC, Augustoqtn commented
confere?

2021-04-27 17:35 UTC, Augustoqtn commented
@mjacobus

2021-04-27 17:41 UTC, mjacobus commented
Confere

2021-05-11 12:28 UTC, mjacobus commented on package.json
> +    "popper.js": "^1.16.1"
```
yarn add bootstrap
yarn add jquery
yarn add popper
```